// Emits ui-loops/l1/<dir>/{index.html,tokens.css,style.css,fonts/*.woff2} from ui-loops/fixture.json.
// Usage: node build.mjs [d1 d2 d3]
import fs from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'
import { palettes } from './palettes.mjs'
import { oklchToRgb, toHex } from './colour.mjs'
import { renderD1 } from './d1.mjs'
import { renderD2 } from './d2.mjs'
import { renderD3 } from './d3.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const which = process.argv.slice(2).length ? process.argv.slice(2) : ['d1', 'd2', 'd3']

const FONTS = {
  d1: [
    { fam: 'Archivo', pkg: 'archivo', w: [600, 700], token: 'display' },
    { fam: 'Source Sans 3', pkg: 'source-sans-3', w: [400, 600, 700], token: 'body' },
    { fam: 'IBM Plex Mono', pkg: 'ibm-plex-mono', w: [400, 500], token: 'figure' },
  ],
  d2: [
    { fam: 'Barlow Condensed', pkg: 'barlow-condensed', w: [500, 600], token: 'display' },
    { fam: 'Barlow', pkg: 'barlow', w: [400, 500, 600], token: 'body' },
    { fam: 'Fragment Mono', pkg: 'fragment-mono', w: [400], token: 'figure' },
  ],
  d3: [
    { fam: 'Newsreader', pkg: 'newsreader', w: [400, 600, 700], styles: { 400: ['normal', 'italic'] }, token: 'display' },
    { fam: 'Alegreya Sans', pkg: 'alegreya-sans', w: [400, 500, 700], token: 'body' },
  ],
}
const SCALE = {
  d1: { radius: '2px', figure: 'figure', extra: '' },
  d2: { radius: '0', figure: 'figure', extra: '' },
  d3: { radius: '1px', figure: 'body', extra: '' },
}
const RENDER = { d1: renderD1, d2: renderD2, d3: renderD3 }

function tokensCss(key) {
  const p = palettes[key]
  const fonts = FONTS[key]
  let css = `/* tokens.css · ${p.name} · GENERATED by build.mjs from palettes.mjs (OKLCH in comments). Colour and family literals live only here. */\n`
  for (const f of fonts) for (const w of f.w) for (const st of f.styles?.[w] ?? ['normal']) {
    const file = `${f.pkg}-latin-${w}-${st}.woff2`
    css += `@font-face { font-family: "${f.fam}"; font-style: ${st}; font-weight: ${w}; font-display: swap; src: url("fonts/${file}") format("woff2"); }\n`
  }
  css += ':root {\n  color-scheme: ' + p.scheme + ';\n'
  for (const [k, v] of Object.entries(p.tokens)) {
    css += `  --${k}: ${toHex(oklchToRgb(v))}; /* oklch(${v[0]} ${v[1]} ${v[2]}) */\n`
  }
  const fam = Object.fromEntries(fonts.map((f) => [f.token, `"${f.fam}"`]))
  css += `  --font-display: ${fam.display}, sans-serif;\n  --font-body: ${fam.body}, sans-serif;\n`
  css += key === 'd3' ? `  --font-figure: ${fam.body}, sans-serif;\n` : `  --font-figure: ${fam.figure}, monospace;\n`
  if (key === 'd3') css = css.replace('--font-display: "Newsreader", sans-serif', '--font-display: "Newsreader", serif').replace('--font-body: "Alegreya Sans", sans-serif;', '--font-body: "Alegreya Sans", sans-serif;\n  --font-text: "Newsreader", serif;')
  css += `  --radius: ${SCALE[key].radius};\n`
  css += `  --space-1: 0.5rem; --space-2: 1rem; --space-3: 1.5rem; --space-4: 2.5rem; --space-5: 4rem; --space-6: 6rem;\n`
  css += `  --t-sm: 0.875rem; --t-base: 1rem; --t-md: 1.125rem; --t-lg: 1.375rem; --t-xl: 1.75rem; --t-2xl: 2.5rem; --t-3xl: 3.5rem;\n`
  css += `  --ease-out: cubic-bezier(0.22, 0.61, 0.36, 1); --ease-in-out: cubic-bezier(0.65, 0, 0.35, 1); --ease-land: cubic-bezier(0.16, 1, 0.3, 1);\n}\n`
  return css
}

for (const key of which) {
  const dir = resolve(here, key)
  fs.mkdirSync(join(dir, 'fonts'), { recursive: true })
  fs.writeFileSync(join(dir, 'tokens.css'), tokensCss(key))
  const shared = fs.readFileSync(join(here, 'src', 'shared.css'), 'utf8')
  const own = fs.readFileSync(join(here, 'src', `${key}.css`), 'utf8')
  const stamp = own.match(/^\s*(\/\*[\s\S]*?\*\/)/)[1] // the macrostructure stamp stays first; shared base precedes the direction's own rules
  fs.writeFileSync(join(dir, 'style.css'), stamp + '\n' + shared + '\n' + own.slice(own.indexOf(stamp) + stamp.length))
  for (const f of FONTS[key]) for (const w of f.w) for (const st of f.styles?.[w] ?? ['normal']) {
    const file = `${f.pkg}-latin-${w}-${st}.woff2`
    fs.copyFileSync(join(here, 'node_modules', '@fontsource', f.pkg, 'files', file), join(dir, 'fonts', file))
  }
  fs.writeFileSync(join(dir, 'index.html'), RENDER[key]())
  console.log(`built ${key}: ${fs.statSync(join(dir, 'index.html')).size} bytes html`)
}
